### ISSUE TITLE
Can't add the extensions 

### ISSUE THREAD

**Issue by ayah-a** [bricklife/scratch-lego-bluetooth-extensions#22]
I'm a little bit confused about the way I should add the extensions to scratch
can anyone please direct me how to add and use the extensions

**Comment by alm-2000** [comment]
If you compiled scratch-gui as described here https://github.com/scratchfoundation/scratch-gui/wiki/Getting-Started
You need to clone repo to same folder
`git clone https://github.com/bricklife/scratch-lego-bluetooth-extensions`
and do 
```
npm run build
npm run register
npm run start
```

**Comment by car123134** [comment]
> If you compiled scratch-gui as described here https://github.com/scratchfoundation/scratch-gui/wiki/Getting-Started You need to clone repo to same folder `git clone https://github.com/bricklife/scratch-lego-bluetooth-extensions` and do
> 
> ```
> npm build
> npm register
> npm start
> ```


I have the same problem when I do npm start 
it says 

```
 scratch-lego-bluetooth-extensions@0.1.0 start
 cd ../scratch-gui && npm run start

'npm' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by alm-2000** [comment]
[car123134](https://github.com/car123134), npm is part of Node 12 

You must complete the prerequisites:
Node 12 (e.g. brew install node)
        If you have multiple versions of Node, you can switch between them using [nvm](https://github.com/nvm-sh/nvm#install--update-script) on Mac or https://github.com/coreybutler/nvm-windows on windows
    Git (e.g. brew install git)
    GitHub account with SSH key set up

**Comment by car123134** [comment]
> [car123134](https://github.com/car123134), npm is part of Node 12
> 
> You must complete the prerequisites: Node 12 (e.g. brew install node) If you have multiple versions of Node, you can switch between them using [nvm](https://github.com/nvm-sh/nvm#install--update-script) on Mac or https://github.com/coreybutler/nvm-windows on windows Git (e.g. brew install git) GitHub account with SSH key set up


I fixed that Issue i have another issue 

I added the extension to scratch and when i run npm start . it starts but when I press add extension it only shows the default

**Comment by alm-2000** [comment]
Dou You call
```
npm build
npm register
npm start
```
from extension folder?

**Comment by car123134** [comment]
> Dou You call
> 
> ```
> npm build
> npm register
> npm start
> ```
> 
> from extension folder?

yes but I think something is going wrong when I type npm register 


```
F:\temp\why\scratch-lego-bluetooth-extensions>npm register
Unknown command: "register"


Did you mean this?
  npm run register # run the "register" package script
To see a list of supported npm commands, run:
  npm help

F:\temp\why\scratch-lego-bluetooth-extensions>npm run register

> scratch-lego-bluetooth-extensions@0.1.0 register
> npm run register:legoble && npm run register:spikeessential && npm run register:legoremote && npm run register:controlplus && npm run register:poweredup && npm run register:duplotrain && npm run register:legopeach && npm run register:legoluigi && npm run register:legomario


> scratch-lego-bluetooth-extensions@0.1.0 register:legoble
> node ./scripts/register.js --link -C --id="legoble" --block="./scratch-vm/src/extensions/scratch3_legoble" --entry="./scratch-gui/src/lib/libraries/extensions/legoble" --gui="../scratch-gui"

node:fs:1808
  binding.symlink(
          ^

Error: EPERM: operation not permitted, symlink 'F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_legoble' -> 'F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_legoble'
    at Object.symlinkSync (node:fs:1808:11)
    at makeSymbolickLink (F:\temp\why\scratch-lego-bluetooth-extensions\scripts\register.js:55:8)
    at Object.<anonymous> (F:\temp\why\scratch-lego-bluetooth-extensions\scripts\register.js:135:5)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
  path: 'F:\\temp\\why\\scratch-lego-bluetooth-extensions\\scratch-vm\\src\\extensions\\scratch3_legoble',
  dest: 'F:\\temp\\why\\scratch-gui\\node_modules\\scratch-vm\\src\\extensions\\scratch3_legoble'
}

Node.js v22.12.0
```

**Comment by alm-2000** [comment]
Yes, sorry, I made a mistake. Of course `npm run register`
Symlink issue in windows sometimes happens in npm. For example if youy FS is not NTFS of src file is not exist of folder of dst file is not exist or dest file is exist or...

You could try [this](https://stackoverflow.com/questions/42433649/npm-install-error-eperm-operation-not-permitted-symlink-mkdirp-bin-cmd-js)
Or try to make symlink by `mklink /j ` from F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_* to F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_*

Or copy all files F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_* to F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_*

But in the latter case, you will most likely need to manually edit the scripts in these folders and replace the paths in the `require(' `functions

**Comment by car123134** [comment]
> Yes, sorry, I made a mistake. Of course `npm run register` Symlink issue in windows sometimes happens in npm. For example if youy FS is not NTFS of src file is not exist of folder of dst file is not exist or dest file is exist or...
> 
> You could try [this](https://stackoverflow.com/questions/42433649/npm-install-error-eperm-operation-not-permitted-symlink-mkdirp-bin-cmd-js) Or try to make symlink by `mklink /j ` from F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_* to F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_*
> 
> Or copy all files F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_* to F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_*
> 
> But in the latter case, you will most likely need to manually edit the scripts in these folders and replace the paths in the `require(' `functions


i copied the files from

F:\temp\why\scratch-lego-bluetooth-extensions\scratch-vm\src\extensions\scratch3_*
to
F:\temp\why\scratch-gui\node_modules\scratch-vm\src\extensions\scratch3_*

when you said 

> But in the latter case, you will most likely need to manually edit the scripts in these > folders and replace the paths in the require(' functions


what do you mean i don't understand

you mean i need  to change something in

F:\temp\why\scratch-lego-bluetooth-extensions\scripts 

I copied the files manually like you said I did the register command I think still the same error or whatever it said  I started after and see the same result nothing the default

**Comment by alm-2000** [comment]
Maybe I can tell you another way.
Delete directories that you copied
And change  scratch-lego-bluetooth-extensions/package.json
Delete `--link ` parameter in each `register` sections.  
and try again run register and start   

don't think about "in the require(' functions" yet

Actually I compiled it under Linux. But then I copied the already compiled code to Windows and it works in both systems. So I can miss some problems when compiling in Windows

**Comment by car123134** [comment]
> Maybe I can tell you another way. Delete directories that you copied And change scratch-lego-bluetooth-extensions/package.json Delete `--link ` parameter in each `register` sections. and try again run register and start
> 
> don't think about "in the require(' functions" yet
> 
> Actually I compiled it under Linux. But then I copied the already compiled code to Windows and it works in both systems. So I can miss some problems when compiling in Windows

I believe it didn't have the error when I did the register
but this time it had an error when it started

and can i use wsl ubuntu distro
 

 the error 


cached modules 25.9 MiB (javascript) 61.9 MiB (asset) [cached] 3603 modules
runtime modules 126 KiB 76 modules

ERROR in ../scratch-vm/src/extensions/scratch3_controlplus/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_controlplus'
 @ ../scratch-vm/src/extension-support/extension-manager.js 32:38-83
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_controlplus/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_controlplus'
 @ ../scratch-vm/src/extension-support/extension-manager.js 32:38-83
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 4:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 5:14-36
Module not found: Error: Can't resolve './lib/color' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 6:26-61
Module not found: Error: Can't resolve './lib/setup-translations' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoble/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoble'
 @ ../scratch-vm/src/extension-support/extension-manager.js 35:34-75
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoble/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoble'
 @ ../scratch-vm/src/extension-support/extension-manager.js 35:34-75
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoluigi/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoluigi'
 @ ../scratch-vm/src/extension-support/extension-manager.js 28:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoluigi/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoluigi'
 @ ../scratch-vm/src/extension-support/extension-manager.js 28:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legomario/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legomario'
 @ ../scratch-vm/src/extension-support/extension-manager.js 27:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legomario/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legomario'
 @ ../scratch-vm/src/extension-support/extension-manager.js 27:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legopeach/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legopeach'
 @ ../scratch-vm/src/extension-support/extension-manager.js 29:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legopeach/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legopeach'
 @ ../scratch-vm/src/extension-support/extension-manager.js 29:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 4:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 5:14-36
Module not found: Error: Can't resolve './lib/color' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 6:26-61
Module not found: Error: Can't resolve './lib/setup-translations' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_poweredup/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_poweredup'
 @ ../scratch-vm/src/extension-support/extension-manager.js 31:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_poweredup/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_poweredup'
 @ ../scratch-vm/src/extension-support/extension-manager.js 31:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_spikeessential/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_spikeessential'
 @ ../scratch-vm/src/extension-support/extension-manager.js 34:41-89
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_spikeessential/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_spikeessential'
 @ ../scratch-vm/src/extension-support/extension-manager.js 34:41-89
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

20 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.97.1 compiled with 20 errors in 6226 ms

**Comment by alm-2000** [comment]
Ok, it is good :-)
I had the same problem when building on Linux 
And I just copy folder like F:\temp\why\scratch-vm to  scratch-gui\node_modules\scratch-vm
Let's try it :-)

**Comment by car123134** [comment]
> Ok, it is good :-) I had the same problem when building on Linux And I just copy folder like F:\temp\why\scratch-vm to scratch-gui\node_modules\scratch-vm Let's try it :-)

now i have 18 errors 


cached modules 25.9 MiB (javascript) 61.9 MiB (asset) [cached] 3609 modules
runtime modules 126 KiB 76 modules

ERROR in ../scratch-vm/src/extensions/scratch3_controlplus/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_controlplus'
 @ ../scratch-vm/src/extension-support/extension-manager.js 32:38-83
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_controlplus/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_controlplus'
 @ ../scratch-vm/src/extension-support/extension-manager.js 32:38-83
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 4:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 5:14-36
Module not found: Error: Can't resolve './lib/color' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_duplotrain/index.js 6:26-61
Module not found: Error: Can't resolve './lib/setup-translations' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_duplotrain'
 @ ../scratch-vm/src/extension-support/extension-manager.js 30:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoluigi/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoluigi'
 @ ../scratch-vm/src/extension-support/extension-manager.js 28:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoluigi/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoluigi'
 @ ../scratch-vm/src/extension-support/extension-manager.js 28:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legomario/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legomario'
 @ ../scratch-vm/src/extension-support/extension-manager.js 27:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legomario/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legomario'
 @ ../scratch-vm/src/extension-support/extension-manager.js 27:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legopeach/index.js 1:24-58
Module not found: Error: Can't resolve './lib/mario-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legopeach'
 @ ../scratch-vm/src/extension-support/extension-manager.js 29:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legopeach/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legopeach'
 @ ../scratch-vm/src/extension-support/extension-manager.js 29:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 4:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 5:14-36
Module not found: Error: Can't resolve './lib/color' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_legoremote/index.js 6:26-61
Module not found: Error: Can't resolve './lib/setup-translations' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_legoremote'
 @ ../scratch-vm/src/extension-support/extension-manager.js 33:37-81
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_poweredup/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_poweredup'
 @ ../scratch-vm/src/extension-support/extension-manager.js 31:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_poweredup/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_poweredup'
 @ ../scratch-vm/src/extension-support/extension-manager.js 31:36-79
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_spikeessential/index.js 1:22-54
Module not found: Error: Can't resolve './lib/ble-base-blocks' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_spikeessential'
 @ ../scratch-vm/src/extension-support/extension-manager.js 34:41-89
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

ERROR in ../scratch-vm/src/extensions/scratch3_spikeessential/index.js 2:12-32
Module not found: Error: Can't resolve './lib/hub' in 'F:\temp\why\scratch-vm\src\extensions\scratch3_spikeessential'
 @ ../scratch-vm/src/extension-support/extension-manager.js 34:41-89
 @ ../scratch-vm/src/virtual-machine.js 11:25-73
 @ ../scratch-vm/src/index.js 1:23-51
 @ ./src/containers/controls.jsx 8:0-28 54:27-29
 @ ./src/playground/blocks-only.jsx 4:0-50 14:44-52

18 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.97.1 compiled with 18 errors in 4017 ms

**Comment by alm-2000** [comment]
Where do you call `npm start` ?
Try call `npm start ` from F:\temp\why\scratch-gui folder

**Comment by car123134** [comment]
no i did it from F:\temp\why\scratch-lego-bluetooth-extensions 

i did it now from F:\temp\why\scratch-gui but  still the same errors

**Comment by alm-2000** [comment]
Do You have a lib folder inside F:\temp\why\scratch-vm\src\extensions\scratch3_controlplus? (and other from this extension)

**Comment by car123134** [comment]
it is a file not a folder  does it need to be a folder 
![image](https://github.com/user-attachments/assets/508fec10-b14d-4195-8f9c-435096c62308)
![image](https://github.com/user-attachments/assets/6d74e857-9ec5-4b51-9731-37982cccef11)

**Comment by alm-2000** [comment]
Yes, it should be a link to the scratch3_legoble/lib folder, but we know there's something wrong with creating links
just copy the scratch3_legoble/lib folder instead of this "lib" file

**Comment by car123134** [comment]
thank you it works 

also is there a way to add Spike Prime as well ?

**Comment by alm-2000** [comment]
I don't know, because I don't have SPIKE Prime Hub. 
But it is written in the readme file "LEGO Education SPIKE Prime Hub (Legacy) <- Not working on Windows"

I used this extension to program one wedo2.0 hub together with two PoweredUp hubs in one project

**Comment by car123134** [comment]
ok thank you for the help
